SET client_encoding = 'windows-1250';

CREATE TABLE irEcoRegions (
  ECO_ID_U INTEGER NULL,
  ECO_CODE VARCHAR(16) NULL,
  ECO_NAME VARCHAR(100) NULL,
  ECO_NUM INTEGER NULL,
  ECODE_NAME VARCHAR(120) NULL,
  CLS_CODE INTEGER NULL,
  ECO_NOTES VARCHAR(250) NULL,
  WWF_REALM VARCHAR(2) NULL,
  WWF_REALM2 VARCHAR(15) NULL,
  WWF_MHTNUM INTEGER NULL,
  WWF_MHTNAM VARCHAR(70) NULL,
  RealmMHT VARCHAR(4) NULL,
  ER_UPDATE VARCHAR(15) NULL,
  ER_DATE_U VARCHAR(12) NULL,
  ER_RATION VARCHAR(100) NULL,
  SOURCEDATA VARCHAR(50) NULL
);
