SET client_encoding = 'windows-1250';

COPY irEcoRegions(ECO_ID_U, ECO_CODE, ECO_NAME, ECO_NUM, ECODE_NAME, CLS_CODE, ECO_NOTES, WWF_REALM, WWF_REALM2, WWF_MHTNUM, WWF_MHTNAM, RealmMHT, ER_UPDATE, ER_DATE_U, ER_RATION, SOURCEDATA) FROM stdin;
\.
