SET client_encoding = 'windows-1250';

CREATE TABLE irFreshWater (
  ECO_ID INTEGER NULL,
  ECOREGION VARCHAR(128) NULL,
  MHT_TXT VARCHAR(75) NULL,
  MHT_NO INTEGER NULL,
  OLD_ID INTEGER NULL,
  ECO_ID_U INTEGER NULL
);
