SET client_encoding = 'windows-1250';

CREATE TABLE IRN_roads (
  MED_DESCRI VARCHAR(254) NULL,
  RTT_DESCRI VARCHAR(254) NULL,
  F_CODE_DES VARCHAR(10) NULL,
  ISO VARCHAR(7) NULL,
  ISOCOUNTRY VARCHAR(54) NULL
);
