SET client_encoding = 'windows-1250';

CREATE TABLE IRN_adm2 (
  ID_0 INTEGER NULL,
  ISO VARCHAR(3) NULL,
  NAME_0 VARCHAR(75) NULL,
  ID_1 INTEGER NULL,
  NAME_1 VARCHAR(75) NULL,
  ID_2 INTEGER NULL,
  NAME_2 VARCHAR(75) NULL,
  VARNAME_2 VARCHAR(150) NULL,
  NL_NAME_2 VARCHAR(75) NULL,
  HASC_2 VARCHAR(15) NULL,
  CC_2 VARCHAR(15) NULL,
  TYPE_2 VARCHAR(50) NULL,
  ENGTYPE_2 VARCHAR(50) NULL,
  VALIDFR_2 VARCHAR(25) NULL,
  VALIDTO_2 VARCHAR(25) NULL,
  REMARKS_2 VARCHAR(100) NULL,
  Shape_Leng FLOAT NULL,
  Shape_Area FLOAT NULL
);
