SET client_encoding = 'windows-1250';

CREATE TABLE IRN_adm1 (
  ID_0 INTEGER NULL,
  ISO VARCHAR(3) NULL,
  NAME_0 VARCHAR(75) NULL,
  ID_1 INTEGER NULL,
  NAME_1 VARCHAR(75) NULL,
  VARNAME_1 VARCHAR(150) NULL,
  NL_NAME_1 VARCHAR(50) NULL,
  HASC_1 VARCHAR(15) NULL,
  CC_1 VARCHAR(15) NULL,
  TYPE_1 VARCHAR(50) NULL,
  ENGTYPE_1 VARCHAR(50) NULL,
  VALIDFR_1 VARCHAR(25) NULL,
  VALIDTO_1 VARCHAR(25) NULL,
  REMARKS_1 VARCHAR(125) NULL,
  Shape_Leng FLOAT NULL,
  Shape_Area FLOAT NULL
);
