SET client_encoding = 'windows-1250';

CREATE TABLE irProvinces (
  adm1_code VARCHAR(10) NULL,
  Shape_Leng INTEGER NULL,
  Shape_Area INTEGER NULL,
  diss_me INTEGER NULL,
  adm1_code_ VARCHAR(10) NULL,
  iso_3166_2 VARCHAR(10) NULL,
  wikipedia VARCHAR(254) NULL,
  sr_sov_a3 VARCHAR(3) NULL,
  sr_adm0_a3 VARCHAR(3) NULL,
  iso_a2 VARCHAR(2) NULL,
  adm0_sr INTEGER NULL,
  admin0_lab INTEGER NULL,
  name VARCHAR(100) NULL,
  name_alt VARCHAR(200) NULL,
  name_local VARCHAR(200) NULL,
  type VARCHAR(100) NULL,
  type_en VARCHAR(100) NULL,
  code_local VARCHAR(50) NULL,
  code_hasc VARCHAR(10) NULL,
  note VARCHAR(254) NULL,
  hasc_maybe VARCHAR(50) NULL,
  region VARCHAR(100) NULL,
  region_cod VARCHAR(50) NULL,
  region_big VARCHAR(200) NULL,
  big_code VARCHAR(50) NULL,
  provnum_ne INTEGER NULL,
  gadm_level INTEGER NULL,
  check_me INTEGER NULL,
  scalerank INTEGER NULL,
  datarank INTEGER NULL,
  abbrev VARCHAR(10) NULL,
  postal VARCHAR(10) NULL,
  area_sqkm INTEGER NULL,
  sameascity INTEGER NULL,
  labelrank INTEGER NULL,
  featurecla VARCHAR(50) NULL,
  admin VARCHAR(200) NULL,
  name_len INTEGER NULL,
  mapcolor9 INTEGER NULL,
  mapcolor13 INTEGER NULL
);
