SET client_encoding = 'windows-1250';

CREATE TABLE irRoads (
  scalerank INTEGER NULL,
  featurecla VARCHAR(30) NULL,
  type VARCHAR(50) NULL,
  sov_a3 VARCHAR(3) NULL,
  note VARCHAR(50) NULL,
  edited VARCHAR(50) NULL,
  name VARCHAR(25) NULL,
  namealt VARCHAR(25) NULL,
  namealtt VARCHAR(30) NULL,
  routeraw VARCHAR(50) NULL,
  question INTEGER NULL,
  length_km INTEGER NULL,
  toll INTEGER NULL,
  ne_part VARCHAR(50) NULL,
  label VARCHAR(50) NULL,
  label2 VARCHAR(50) NULL,
  local VARCHAR(30) NULL,
  localtype VARCHAR(30) NULL,
  localalt VARCHAR(30) NULL,
  labelrank INTEGER NULL,
  ignore INTEGER NULL,
  add INTEGER NULL,
  rwdb_rd_id INTEGER NULL,
  orig_fid INTEGER NULL,
  prefix VARCHAR(5) NULL,
  uident INTEGER NULL,
  continent VARCHAR(50) NULL,
  expressway INTEGER NULL,
  level VARCHAR(50) NULL
);
