SET client_encoding = 'windows-1250';

CREATE TABLE irShahrestan (
  ADM2_CODE INTEGER NULL,
  ADM2_NAME VARCHAR(100) NULL,
  STR2_YEAR INTEGER NULL,
  EXP2_YEAR INTEGER NULL,
  ADM1_CODE INTEGER NULL,
  ADM1_NAME VARCHAR(100) NULL,
  STATUS VARCHAR(37) NULL,
  DISP_AREA VARCHAR(3) NULL,
  ADM0_CODE INTEGER NULL,
  ADM0_NAME VARCHAR(100) NULL,
  Shape_Leng INTEGER NULL,
  Shape_Area INTEGER NULL
);
