SET client_encoding = 'windows-1250';

CREATE TABLE USA_water_areas_dcw (
  ISO VARCHAR(7) NULL,
  COUNTRY VARCHAR(54) NULL,
  F_CODE_DES VARCHAR(254) NULL,
  HYC_DESCRI VARCHAR(254) NULL,
  NAME VARCHAR(254) NULL
);
